#!/bin/bash
# QUICK START - The Marrrweco

echo "==========================================="
echo "🎉  THE MARRRWECO - QUICK START"
echo "==========================================="
echo ""
echo "Bem-vindo! Você tem uma aplicação completa!"
echo ""
echo "📁 Localização: $(pwd)"
echo ""
echo "==========================================="
echo "🚀 INICIANDO EM 3 PASSOS"
echo "==========================================="
echo ""

echo "✅ Passo 1: Verificando Docker..."
if ! command -v docker &> /dev/null; then
    echo "❌ Docker não encontrado. Instale em: https://docker.com"
    exit 1
fi
echo "✅ Docker encontrado"
echo ""

echo "Passo 2: Iniciando containers..."
docker-compose up -d
echo "✅ Containers iniciados"
echo ""

echo "⏳ Passo 3: Aguardando banco de dados (será rápido)..."
sleep 15
echo "✅ Sistema pronto!"
echo ""

echo "==========================================="
echo "🌐 ACESSE AQUI:"
echo "==========================================="
echo ""
echo "🎨 Frontend:  http://localhost:3000"
echo "🔧 Backend:   http://localhost:8000"
echo ""

echo "🔑 USE ESTAS CREDENCIAIS:"
echo ""
echo "👤 CLIENTE:"
echo "   Email: joao@email.com"
echo "   Senha: password"
echo ""
echo "🎤 PROMOTER:"
echo "   Email: maria@promoter.com"  
echo "   Senha: password"
echo ""
echo "💼 ATLÉTICA:"
echo "   Email: atletica@uni.com"
echo "   Senha: password"
echo ""

echo "==========================================="
echo "📚 DOCUMENTAÇÃO:"
echo "==========================================="
echo ""
echo "👉 Leia PRIMEIRO: WELCOME.md"
echo "   Guia completo para começar"
echo ""
echo "📖 Documentação adicional:"
echo "   - SETUP.md       : Instalação passo a passo"
echo "   - API.md         : Endpoints da aplicação"
echo "   - README.md      : Overview do projeto"
echo "   - CHECKLIST.md   : O que foi implementado"
echo ""

echo "==========================================="
echo "💡 DICAS RÁPIDAS:"
echo "==========================================="
echo ""
echo "Ver status dos containers:"
echo "  docker-compose ps"
echo ""
echo "Ver logs em tempo real:"
echo "  docker-compose logs -f"
echo ""
echo "Parar a aplicação:"
echo "  docker-compose down"
echo ""
echo "Usar Makefile (se instalado):"
echo "  make help"
echo ""

echo "==========================================="
echo "✅ TUDO PRONTO!"
echo "==========================================="
echo ""
echo "Abra agora: http://localhost:3000"
echo ""
echo "🎊 Divirta-se desenvolvendo! 🎊"
echo ""
